### ISSUE TITLE
he always finds only one couple, that's all

### ISSUE THREAD

**Issue by MoriZalev** [gkayode/crypto_arbitrage_bot#4]
![image](https://user-images.githubusercontent.com/106540747/172017881-30781339-ebab-490f-838b-781d074d1deb.png)
he always finds only one couple, that's all

**Comment by gkayode** [comment]
Yes, this is because that's the only pair with a percent change greater than 14% (the benchmark), at that moment. If we set the benchmark to say 1%. There should be other pairs as shown below:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/52835575/172019608-4506577e-d267-49dd-8cbf-0cc4e503435b.png">

Like and fork if you found it helpful

**Comment by MoriZalev** [comment]
Is it possible to add exchanges like: Binance, Bybit, Crypto com? Will you update this script?

**Comment by gkayode** [comment]
Yes it is possible to include multiple exchanges. These two are the only ones I have had prior experience with that’s why they were chosen.

As at now I’m working on other projects, so I won’t be updating the script anytime soon.
